version: "2"
services:
  web:
    image: arjun0419/reviews-proxy
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
  redis:
    image: 'redis:latest'
    ports: 
      - "6379:6379"